### ISSUE TITLE
Link error: undefined reference to `jrtplib::RTPFakeTransmitter::AbortWait()'

### ISSUE THREAD

**Issue by rpici** [j0r1/JRTPLIB#1]
On Linux, after compiling and installing, when I link against the library (-ljrtp), I get the following link error:

`/usr/local/lib/libjrtp.so: undefined reference to 'jrtplib::RTPFakeTransmitter::AbortWait()'`

To fix it, in src/extratransmitters/rtpfaketransmitter.cpp, underneath `RTPFakeTransmitter::WaitForIncoingData()`,  I insert the following member function implementation:

`int RTPFakeTransmitter::AbortWait()
{
return ERR_RTP_FAKETRANS_WAITNOTIMPLEMENTED;
}`

then I recompile and reinstall the library. 

This eliminates the linker error, but is this the proper way to do this? Am I doing something else wrong to get the linker error in the first place?

**Comment by j0r1** [comment]
Funny that you mention this, I just saw it myself :) It is the right way to fix it, I just pushed it.
