### ISSUE TITLE
RTPSession copy constructor is broken

### ISSUE THREAD

**Issue by suhbataar** [j0r1/JRTPLIB#13]
RTPSession can be copied with the default copy constructor, which however does the wrong thing. It copies the pointer to RTPRandom instead of cloning the pointed-to object. When one of the copies is destroyed, it deletes the RTPRandom, which will result in access violation or double delete, depending on how the other copy is used.

Probably RTPSession is not meant to be copied, so I suggest you disable the copy constructor and copy assignment operator as described [here](https://stackoverflow.com/questions/6077143/disable-copy-constructor).

**Comment by j0r1** [comment]
I've made changes to a few header files. Does that work for you?

**Comment by suhbataar** [comment]
Yes, thanks for fixing! And thank you for this great library, it enabled me to create a simple RTP-Server very quickly.
