### ISSUE TITLE
x64 not working

### ISSUE THREAD

**Issue by dorin-ionita** [j0r1/JRTPLIB#17]
It seems that the .lib files created as per the video tutorial you provided are x86. Is there anyway to make them work within a x64 project?

**Comment by dorin-ionita** [comment]
More precisely, VS 2017 says "module machine type 'x86' conflicts with target machien type 'x64'", with regard to jrtplib_d.lib

**Comment by j0r1** [comment]
You need to tell cmake to create x64 code, see e.g. https://cmake.org/cmake/help/v3.12/generator/Visual%20Studio%2015%202017.html

**Comment by dorin-ionita** [comment]
Did as you say and when trying to build jthread in Visual Studio it says module machine type 'x64' conflicts with target machine type 'x86' for file jmutex.obj

**Comment by j0r1** [comment]
Yes, you need to build an x64 version of jthread as well, and make sure that version is used for linking

**Comment by dorin-ionita** [comment]
Solved. 

For the record, in case anybody faces this problem in the future:
I guess I wasn't doing all the settings for x64 in CMake. I didn't have to add any other Entry by clicking "Add Entry", CMake asked me for a generator anyway and I selected x64 there.
