### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ktb92677** [j0r1/JRTPLIB#28]
Hey, so I am incorporating your library into my program right now and I am receiving the following compile time error:

/usr/local/include/jrtplib3/rtptimeutilities.h:92:17: error: expected unqualified-id before numeric constant
  static RTPTime CurrentTime();
                 ^
/usr/local/include/jrtplib3/rtptimeutilities.h:268:25: error: expected unqualified-id before numeric constant
 inline RTPTime RTPTime::CurrentTime()

I have been able to narrow down the issue just a little bit. It seems to only pop up when "rtpsession.h" is included in more than one file. Any help would be greatly appreciated!

**Comment by ktb92677** [comment]
Okay, well I think I've narrowed down the issue a little bit. My program integrates with the XTest library. Specifically I am using this function: XTestFakeButtonEvent. This function takes the following variable as an argument: "CurrentTime". I believe these may be conflicting.

**Comment by j0r1** [comment]
It seems that CurrentTime is a define in X.h, defined as 0. Is it possible to separate the X and jrtplib stuff so that they don't conflict? Alternatively, perhaps you can undef CurrentTime after including X.h?

**Comment by ktb92677** [comment]
Hmm, I suppose I could do these things. Please do not take this the wrong way at all but wouldn't it make a bit more sense to not have variable names in your program as generic as "CurrentTime"? I partly fault xlib for their poor naming conventions as well, but there might come another library with a variable of the same name that could again conflict with your library... Just a thought.

**Comment by j0r1** [comment]
I don't see what's wrong with naming a function in the way I see fit. It's even in the namespace of a class, which in itself is in the jrtplib namespace. The problem is that it's a define in the X header file, so the preprocessor will change it to something else and all of a sudden the code doesn't make sense any more.

I'm not going to change it all of a sudden in the library: this would break a lot of code.

**Comment by ktb92677** [comment]
Okay :) Hey your library is great by the way. Like I said before I really didn't want my comment to be taken the wrong way, I just wanted to see if it was a possibility to adjust. Regardless for anyone who's reading this post in the future the following changes fixed the code:

```
#undef CurrentTime
#undef None
```

Put this behind any #include <X11/*> and before any #include "rtp*". Also where ever you use CurrentTime in any xlib related function replace it with 0.
