### ISSUE TITLE
[Not an issue] Memory leak in RTPInternalSourceData, but only when using the not recommended OnRTPPacket

### ISSUE THREAD

**Issue by mihaicodrean** [j0r1/JRTPLIB#5]
Hi!

The packetlist from RTPInternalSourceData grows indefinitely for me, using JRTPLib 3.8.1. I've checked the code and the only place where items get removed from the packetlist is in ProcessRTPPacket, when not validated / "still on probation".

Am I doing something wrong? What should I check?

Thanks in advance,
Mihai

**Comment by j0r1** [comment]
How are you obtaining the packets?

**Comment by mihaicodrean** [comment]
I'm sending them using [Conference XP](https://github.com/conferencexp/conferencexp/tree/master/MSR.LST.Net.Rtp), as multicast. JRTPLib is used as the receiver.

**Comment by j0r1** [comment]
What I meant was: which functions of the library are you calling to obtain the received RTP packets?

**Comment by mihaicodrean** [comment]
I am handling the received packets in the OnRTPPacket method overridden in a class derived from RTPSession. Otherwise, there's nothing special that I do. Just setting the session parameters, Create (session), SetReceiveMode, AddToAcceptList & JoinMulticastGroup.

Do you happen to have an RTP client app to verify the leaking behavior yourself? Or have a brief look at the usage of "packetlist" in RTPInternalSourceData in this respect?

**Comment by j0r1** [comment]
Well, the [OnRTPPacket](http://jrtplib.readthedocs.io/en/stable/classjrtplib_1_1RTPSession.html#a06463679e5ca4033e284ba91bb65f13f)  function was not meant for that. In the 3.8.1 version, you'll have to iterate over the sources to extract the packets. In the latest version you can override [OnValidatedRTPPacket](http://jrtplib.readthedocs.io/en/stable/classjrtplib_1_1RTPSession.html#aead4d58091eab72eaea40df644ed680f), which would probably require less changes to your code.

**Comment by mihaicodrean** [comment]
Ah, thanks much! I'll definitely upgrade then and switch to OnValidateRTPPacket. I'll get back later today on the result.

**Comment by mihaicodrean** [comment]
Works perfectly, thanks again! I've renamed the issue title accordingly.
