### ISSUE TITLE
jrtp not receiving packets on Linux/ARM when sending from a remote pc

### ISSUE THREAD

**Issue by Findus79** [j0r1/JRTPLIB#8]
Hi,

I included jrtplib into my project, and it is working fine on Windows. Sending RTP data over a network and receiving.
When using the same program built for Linux on ARM (Nvidia Jetson), I only receive packets when sending from the same machine as where the receiving program is run. It doesn't matter if I listen on 127.0.0.1, 0.0.0.0 or the network interface.
I already checked with strace, sockets are opened, it looks the same for both variations (sending from local and remote, data is read from the socket), yet when sending from a remote machine I do not get data from jrtp.

Here's the setup I use for the receiving side:

    jrtplib::RTPUDPv4TransmissionParams transmission_params;
    jrtplib::RTPSessionParams session_params;

    session_params.SetOwnTimestampUnit(1.0 / 90000.0);
    session_params.SetMaximumPacketSize(64000);
    session_params.SetAcceptOwnPackets(false);

    transmission_params.SetPortbase(24710);
    transmission_params.SetRTPReceiveBuffer(1024*1024); // big enough for everything ...

    jrtplib::RTPSession session;
    auto status = session.Create(session_params, &transmission_params);

Does anyone have an idea or encountered a similar problem? Since data is coming from the remote machine (I can see it being read with strace), I am out of ideas here.

thanks for any help
Findus

**Comment by j0r1** [comment]
Hi Findus,

Did you compile jrtplib on the arm device itself, or did you cross compile it? In the first case, the endianness of the system should be detected correctly, but in the second case it can't autodetect and will assume big endian. If the ARM device is actually a little endian one, then this would cause incorrect packets to be formed there and incoming correct packets to be analyzed wrong. For localhost packets the mistake will not be apparent though.

Jori

**Comment by Findus79** [comment]
Good morning,

that was just the right hint I needed. I haven't notices the CMake option until now :) my ARM target indeed is little endian, changing the option fixed my problem :)

Thanks,
